FROM python:3.13

WORKDIR /pyback

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY . .

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

EXPOSE 8000

CMD ["fastapi", "run", "server_agents.py", "--port", "8000"]