FROM python:3.13

WORKDIR /pydb

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY . .

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN python setup_sqlite_db.py
RUN python setup_Chroma_db.py

EXPOSE 9000

CMD ["fastapi", "run", "server_rag.py", "--port", "9000"]